[package]
name = "embed-src"
version = "2.1.4"
edition = "2021"
description = "Embed source files into any text file"
license = "Apache-2.0"
repository = "https://github.com/urmzd/embed-src"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1"
