[package]
name = "embed-it"
version = "2.1.0"
edition = "2021"
description = "Embed source files into any text file"
license = "Apache-2.0"
repository = "https://github.com/urmzd/embed-it"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1"
